### ISSUE TITLE
How about travis ci ?

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#14]
I would prefer to add travis ci to your project to prevent code style faults and passing tests.

**Comment by Techworker** [comment]
I activated travis, do you have a travis config template that would make sense?

**Comment by robinlehrmann** [comment]
I will working on it. But first we should fix #13 maybe I would add some tools like: phpstan (for static code analytics), deptrac (for architecture rules) and php Code Sniffer to check the Code Style.

**Comment by nnsdev** [comment]
An alternative idea could be https://styleci.io 

It checks PRs automatically on code quality, is very well configurable and fixes style automatically after an invalid commit, although this is configurable. It is free for OSS

**Comment by robinlehrmann** [comment]
Thank you for your suggestion @JulienGelmar. But I think it belongs to the developer to commit code. A reason is, that this service change your code automatically and you will not review it, after merge. Due the php-cs-fix make target you can fix code locally.

**Comment by nnsdev** [comment]
You can set StyleCI as you like, you can set it to `only validate`, `automatically fix code`, `open PR after invalid code was found` or `fix code when user presses check button`.

Even if you're not going to use the fixing features, I think it would still be pretty cood to have a tool that can check the code quality without interfering with the code. This makes sure that we will always see if the code has valid codestyle without having to check it for yourself.

**Comment by Techworker** [comment]
So many cool tools out there, we will consider it, thanks.

I do care about a clean code base and code quality, if you had time to explore the lib already you might have recognized that, even though there is still a lot potential for cleanups.

But, after all, my main concern right now is to bring the implementation itself to a state where it can be used by others. If there is a missing comma at the end of an array for better merge-views or an additional \x20 or a bracket on the wrong line.. this does not define the library itself, and it's simple to fix after we are done with basics. And just because a tool says a design decision is not good, there might be reasons for my design decision. Everyone loves a martin fowler textbook like implementation, but in the end the functionality counts. That's why no-one is complaining about libraries like symfony/yaml and everyone is using it even though the code code (like the parser) can be called awful from a perfect-design perspective.  

Refactoring will definitely come before a 1.0 release, and I'm open to all suggestions if they make sense for sure, but we are far ahead of this milestone if we keep concentrating on stuff that is, from my pov, considered `nice 2 have`.

We all love clean code, but we all also love tested libraries that just work. So a tool that will help us executing tests is all we need for now, and if we can get travis up and running fast, it will be travis until we have the need for more.

My 2 cents, maybe a bit offtopic but I wanted to make it clear that this stuff has no priority for me.

**Comment by nnsdev** [comment]
That's perfectly fine and I agree, but StyleCI is setup in under a minute, so that might be worth it :P 

In the end it comes down to your decision, I'd love to have it from the get-go, but I'm fine with not having it, as long as everyone is running php-cs-fixer locally :D

**Comment by robinlehrmann** [comment]
@JulienGelmar I think, if a tool changes your code without a developer, you don't have the power over it. We can think about it, yes. But I agree with @Techworker. We can collect some improvments, but we should follow a MVP. The functionality and the tests of the code comes first.
