### ISSUE TITLE
We should refactor the .gitignore file

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#19]
You have some system specific files in your .gitignore file. We should talk about it.

**Comment by Techworker** [comment]
The `.proc` comes from ccurl, shouldn't be needed. It's just that I had the ccurl binaries inside of the library at the start. Same with the `ccurl` entry.

`node_modules`, `nodesource_setup.sh` and `npm-debug.log` can be removed. There was a keccak-384 workaround with nodejs because `kornrunner/keccak` didn't exist back then.

**Comment by Techworker** [comment]
Removed all unnecessary entries, what do you think? Anything else I should add/remove?

**Comment by robinlehrmann** [comment]
Well done 👍  I think we should also remove the .idea direcotry, because this is ide specific and not project related :)

**Comment by Techworker** [comment]
The result will be a committed .idea folder sooner or later (from me :-P) - but ok, seems like the other libs don't commit it either.

**Comment by Techworker** [comment]
Removed with https://github.com/Techworker/iota-php/commit/988f25fbe3db45cf24f9495fa2129c0b76654e33
