### ISSUE TITLE
Use symfony/serializer component for serialization

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#20]
We can use the symfony serializer component to save some time.

**Comment by Techworker** [comment]
The serialization is pretty simple, will the serializer component be faster than what we have now? I don't want too many dependencies, only when it's really needed. 

I'm not even sure if serialization is needed. My motivation was the kitchen sink example project and, because of the nesting of objects that take place, dumping a getBundle response will most probably kill your process.

**Comment by robinlehrmann** [comment]
You are right. It would be over engineering in this case. I think we can close this issue.
