### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#50]
Hi all, I've ever tried to implement the `IOTA` [client](https://github.com/peter279k/iota.lib.php) with PHP before.

Finally I found this PHP package and it looks great. I decide to archive my repo and try to help this.

Now I want to know is this repo still maintained?

Thanks.

**Comment by Techworker** [comment]
Hi Peter,

I'm the author of most of the code you see here.

The development stopped somehow because of the lack of significant contributions as well as missing adoption. But for sure I'd like to revive it if there is interest!

Most of the stuff used to work, but I think we need to catch up with various developments on the IOTA side. If you are interested in more info about the state of the project get in touch with me on the IOTA discord (@techworker)

Btw. congrats to your library! We might join forces and add some of your stuff to this lib, because eg multisignatures were started but never finished iirc.

**Comment by peter279k** [comment]
Hi @Techworker, thank you for your reply.

Now I've archived my `iota.lib.php` repo and move to this repo.

If possible, can I contribute this repo?

Thanks.

**Comment by Techworker** [comment]
You can, as discussed in discord. Thanks for your interest :+1:
