### ISSUE TITLE
Missing the methods for ValidatorUtil

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#54]
According to the `inputvalidator` on [inputValidator.js](https://github.com/iotaledger/iota.js/blob/develop/lib/utils/inputValidator.js), they're different kind of the input validation methods.

However, there're only two validation methods on `IOTA\Util\ValidatorUtil` class.

I think it should add other validation features so that it can use them to validate some input values.

**Comment by Techworker** [comment]
Since we are using value objects for nearly everything (except for trits, I removed that), the validation is implemented in the constructors of the classes:

For example:

isAddress - https://github.com/iota-php/client/blob/master/src/Type/Address.php#L40
isTrytes - https://github.com/iota-php/client/blob/master/src/Type/Trytes.php#L39
.. and so on

**Comment by peter279k** [comment]
@Techworker, ok. It makes sense and it seems that reorganize the input validations works.

This issue will be closed.
